#禁用默认的error处理
server:
  error:
    whitelabel:
      enabled: false
  port: 8000

spring:
  druid:
    borrowConnectionTimeout: 30000
    maxActive: 20
    maxWait: 10000
    minEvictableIdleTimeMillis: 300000
    minIdle: 3
    password: 1111
    timeBetweenEvictionRunsMillis: 60000
    url: jdbc:mysql://127.0.0.1:3306/user?useSSL=true
    username: root
    validationQuery: SELECT 'x' # 解决mysql8小时问题
  redis:
    host: 192.168.221.100
  mail:
    host: smtp.163.com # 若使用QQ邮箱发送邮件，则需要修改为spring.mail.host=smtp.qq.com，同时spring.mail.password改为QQ邮箱的授权码。
    password: majiafei1 # 授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 13963949859@163.com
  cloud:
    zookeeper:
      connect-string: 192.168.221.100:2181
  application:
    name: user-service
mapper:
  not-empty: true
  identity: MYSQL

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml


#日志
logging:
  level:
    com.ruanmou.user.userserver.mapper: debug

#七牛云的配置
qiniu:
  accessKey: bP_-Q9Pf1smTdlKNrtglsLsgNVLSKy6j0-H-COe7
  secretKey: AqMp9NmfZXd9WwyapxpBczHH-rg8kFYHWvAsKv7k
  bucket: hyson
  urlPrefix: http://pjzbjaw2u.bkt.clouddn.com/